name: CI/CD - Microservicio Node.js + Redis en DOCKER desplegado en EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/demo-microservice-lab
  APP_PORT: ${{ secrets.APP_PORT || 3000 }}

jobs:
  ci:
    name: Integracion continua (build y test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Configuracion Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar las pruebas
        run: NODE_ENV=test npm test

      - name: Iniciar sesion en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir imagen (latest)
        run: docker build -t $IMAGE_NAME:latest .

      - name: Publicar la imagen (latest)
        run: docker push $IMAGE_NAME:latest

  cd:
    name: Entrega y despliegue en EC2
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Instalar cliente SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Cargar clave privada en ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Verificar la clave cargada en el agent
        run: |
          set -euo pipefail
          ssh-add -l -E sha256

      - name: Registrar known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          ssh-keyscan -T 10 -H "$EC2_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Probar conexión SSH (solo publickey, usando agent)
        env:
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          set -euo pipefail
          ssh -o PreferredAuthentications=publickey \
              -o PubkeyAuthentication=yes \
              ec2-user@"$HOST" 'whoami && uname -a'

      - name: Desplegar contenedores en EC2 (App + Redis)
        env:
          HOST: ${{ secrets.EC2_HOST }}
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/demo-microservice-lab:latest
          APP_PORT: ${{ env.APP_PORT }}
        run: |
          set -euo pipefail
          ssh -o IdentitiesOnly=no -o StrictHostKeyChecking=yes \
              ec2-user@"$HOST" "IMAGE='$IMAGE' APP_PORT='$APP_PORT' bash -s" << 'EOF'

          set -euxo pipefail
          if command -v systemctl >/dev/null 2>&1; then
            sudo systemctl start docker || true
          else
            sudo service docker start || true
          fi

          # Crear red si no existe
          docker network inspect appnet >/dev/null 2>&1 || docker network create appnet

          # --- DESPLEGAR REDIS ---
          # Detener y eliminar contenedor Redis si existe
          docker ps -q --filter "name=redis" | grep -q . && docker stop redis || true
          docker ps -aq --filter "name=redis" | grep -q . && docker rm redis || true

          # Crear volumen para persistencia de Redis si no existe
          docker volume inspect redis-data >/dev/null 2>&1 || docker volume create redis-data

          # Iniciar contenedor Redis
          docker run -d --name redis --restart unless-stopped \
            --network appnet \
            -v redis-data:/data \
            redis:7-alpine redis-server --appendonly yes

          # Esperar a que Redis esté listo
          sleep 3

          # --- DESPLEGAR APLICACIÓN ---
          # Detener y eliminar contenedor de la aplicación si existe
          docker ps -q --filter "name=demo-microservice-lab" | grep -q . && docker stop demo-microservice-lab || true
          docker ps -aq --filter "name=demo-microservice-lab" | grep -q . && docker rm demo-microservice-lab || true

          # Descargar la imagen de la aplicación
          docker pull "$IMAGE"

          # Iniciar contenedor de la aplicación con conexión a Redis
          docker run -d --name demo-microservice-lab --restart unless-stopped \
            --network appnet \
            -p 80:"$APP_PORT" \
            -e REDIS_URL=redis://redis:6379 \
            "$IMAGE"

          # Verificar que los contenedores están corriendo
          echo "=== Contenedores activos ==="
          docker ps --filter "name=redis" --filter "name=demo-microservice-lab"

          EOF